// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_xDGcj5ly1MV2NZGSwJ34QTRN8lmdFOI',
    appId: '1:521222395022:web:4f56d3d130532dd305a5df',
    messagingSenderId: '521222395022',
    projectId: 'odoo-fire-219d7',
    authDomain: 'odoo-fire-219d7.firebaseapp.com',
    databaseURL: 'https://odoo-fire-219d7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'odoo-fire-219d7.firebasestorage.app',
    measurementId: 'G-WS59MEW100',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjuNglgK1m7NNyFIL0nAnZNVFUR0nyfa4',
    appId: '1:521222395022:android:fea89ec85c05361f05a5df',
    messagingSenderId: '521222395022',
    projectId: 'odoo-fire-219d7',
    databaseURL: 'https://odoo-fire-219d7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'odoo-fire-219d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfCOlcOw0ewnjx2YtJTuhoxDtquiXKiCM',
    appId: '1:521222395022:ios:327cdb560e1ae2b705a5df',
    messagingSenderId: '521222395022',
    projectId: 'odoo-fire-219d7',
    databaseURL: 'https://odoo-fire-219d7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'odoo-fire-219d7.firebasestorage.app',
    iosBundleId: 'com.example.webviewOdooPush',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfCOlcOw0ewnjx2YtJTuhoxDtquiXKiCM',
    appId: '1:521222395022:ios:327cdb560e1ae2b705a5df',
    messagingSenderId: '521222395022',
    projectId: 'odoo-fire-219d7',
    databaseURL: 'https://odoo-fire-219d7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'odoo-fire-219d7.firebasestorage.app',
    iosBundleId: 'com.example.webviewOdooPush',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_xDGcj5ly1MV2NZGSwJ34QTRN8lmdFOI',
    appId: '1:521222395022:web:4a47410a5d88d97c05a5df',
    messagingSenderId: '521222395022',
    projectId: 'odoo-fire-219d7',
    authDomain: 'odoo-fire-219d7.firebaseapp.com',
    databaseURL: 'https://odoo-fire-219d7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'odoo-fire-219d7.firebasestorage.app',
    measurementId: 'G-LX3EY16HRG',
  );
}
